package com.cts.controller;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import com.cts.dto.NotificationResponseDTO;
import com.cts.service.NotificationService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;

@RestController
@RequestMapping("/api/v1/notifications")
@AllArgsConstructor
@Tag(name = "Notification Controller", description = "Read in-app notifications generated by booking, payment, and cancellation events")
@Slf4j
public class NotificationController {

    private final NotificationService notificationService;

    @Operation(summary = "Get all notifications for a user")
    @GetMapping("/{userId}")
    public ResponseEntity<?> getUserNotifications(@PathVariable Long userId) {

        log.info("Fetching notifications for userId: {}", userId);

        List<NotificationResponseDTO> list1 =
                notificationService.getUserNotifications(userId);

        log.info("Fetched {} notifications for userId: {}", list1.size(), userId);

        return new ResponseEntity<>(list1, HttpStatus.OK);
    }
}